# Site settings
author: elle wilson
title: elle wilson
header-img: img/home-bg.png
email: eleanorwilsonn@gmail.com
copyright_name: elle wilson
description: > # this means to ignore newlines until "baseurl:"
  full-stack developer. based in NYC.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ellewilson96

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
